### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by av012** [jungomi/math-formula-recognition#10]
Hi @jungomi 
While training the model I got this type of error can you give an idea to resolve it

```
Running 100 epochs on cpu
Traceback (most recent call last):

  File "C:\Users\srira\math-formula-recognition\train.py", line 521, in <module>
    main()

  File "C:\Users\srira\math-formula-recognition\train.py", line 444, in main
    gt_train, tokensfile, root=root, crop=options.crop, transform=transformers

  File "C:\Users\srira\math-formula-recognition\dataset.py", line 137, in __init__
    for p, truth in reader

  File "C:\Users\srira\math-formula-recognition\dataset.py", line 126, in <listcomp>
    {

ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by jungomi** [comment]
That means you have an empty line in the ground truth. You need to remove all empty lines, as all lines need to have two columns separated by a tab.

**Comment by av012** [comment]
Hey @jungomi can you please upload the ground truth file. (without empty lines and correct spacing)

**Comment by jungomi** [comment]
In the [CROHME data (from FloydHub)](https://www.floydhub.com/jungomi/datasets/crohme-png) that I provided in the README, there are no empty lines. If you used that, you have modified them at some point, when opening them in an editor.

**Comment by av012** [comment]
Hey @jungomi I have used the data and still getting the same error

Running 100 epochs on cpu
Traceback (most recent call last):

  File "C:\Users\srira\math-formula-recognition\train.py", line 521, in <module>
    main()

  **File "C:\Users\srira\math-formula-recognition\train.py", line 444, in main
    gt_train, tokensfile, root=root, crop=options.crop, transform=transformers**

  **File "C:\Users\srira\math-formula-recognition\dataset.py", line 137, in __init__
    for p, truth in reader**

  **File "C:\Users\srira\math-formula-recognition\dataset.py", line 126, in <listcomp>**
    {

ValueError: not enough values to unpack (expected 2, got 0)




can you please help me to identify errors of line 137 in dataset.py and line line 444 of main.py

**Comment by jungomi** [comment]
As I've said, you need to eliminate the empty lines in the ground truth.

A workaround would be to discard all lines that don't have exactly two columns when loading the data, by changing https://github.com/jungomi/math-formula-recognition/blob/9d68b994f3d9544b7edce94e19bf138ffdfae8ba/dataset.py#L125-L138

to:

```py
self.data = [
    {
        "path": os.path.join(root, line[0] + ext),
        "truth": {
            "text": line[1],
            "encoded": [
                self.token_to_id[START],
                *encode_truth(line[1], self.token_to_id),
                self.token_to_id[END],
            ],
        },
    }
    for line in reader
    if len(line) != 2
]
```

**Comment by av012** [comment]
Hey@jungomi, When I changed the bottom part of the code from  
**for line in reader
    if len(line) != 2**
to
**for line in reader
    if len(line) != 0**

The model started to train

**Comment by jungomi** [comment]
Yes, that was supposed to be either `len(line) != 0` or `len(line) == 2`.

**Comment by ArtificialZeng** [comment]
File "H:\AI_project\math-formula-recognition-master\dataset.py", line 138, in <listcomp>
    if len(line) != 2
NameError: name 'p' is not defined

**Comment by ArtificialZeng** [comment]
> Yes, that was supposed to be either `len(line) != 0` or `len(line) == 2`.

File "H:\AI_project\math-formula-recognition-master\dataset.py", line 138, in <listcomp>
    if len(line) != 2
NameError: name 'p' is not defined
