### ISSUE TITLE
a question about your checkpoint

### ISSUE THREAD

**Issue by xuao1234** [jungomi/math-formula-recognition#14]
I've read some of your checkpoints, would you mind telling me why the dict doesn't have these keys?
![image](https://user-images.githubusercontent.com/53131240/127271210-45434dfb-a826-4772-b767-019c04a500c4.png)
wrt
![image](https://user-images.githubusercontent.com/53131240/127271368-c0feea99-9a0f-4ad2-b6a1-c535d2cba6b5.png)

**Comment by jungomi** [comment]
These checkpoints were trained with an earlier version, which did not record the validation accuracy and loss but only the training ones. `accuracy` corresponds to `train_accuracy` in that case, but `validation_accuracy` doesn't exist.

These are only saved in the checkpoint for statistical reasons, e.g. to plot the evolution of the accuracy over time. Besides that, the checkpoint should be functional.

**Comment by xuao1234** [comment]
Thanks a lot for your review. Here's another thing, your disposed data files on www.floydhub.com are no longer available anymore since this website is shutting down. Can you provide another source?

**Comment by jungomi** [comment]
You can now get the dataset from [Kaggle - chrome-png](https://www.kaggle.com/dataset/3a6d371ee185e037fbc0d4eba075053aeaa54077bda6de3ed1b8f988891fa9ea)
