### ISSUE TITLE
Your dataset can't be reached!

### ISSUE THREAD

**Issue by Wangmou1234** [jungomi/math-formula-recognition#16]
Hello sir, I found that I can't reach the extracted dataset posted in README has been shutted down. Could you fix this problem? Thanks!

**Comment by jungomi** [comment]
Hello, you can now get the dataset from [Kaggle - chrome-png](https://www.kaggle.com/dataset/3a6d371ee185e037fbc0d4eba075053aeaa54077bda6de3ed1b8f988891fa9ea)

**Comment by chenyangMl** [comment]
hi, man, the link of "Kaggle - chrome-png" is not work, Could you figure out about this? Thanks.

**Comment by jungomi** [comment]
Hi, for some reason their link sharing of private datasets doesn't work anymore, so I just made it public and it should now work again.

**Comment by chenyangMl** [comment]
> Hi, for some reason their link sharing of private datasets doesn't work anymore, so I just made it public and it should now work again.

it's work, thanks.
