### ISSUE TITLE
Evaluate Runtime Error

### ISSUE THREAD

**Issue by TDYe123** [jungomi/math-formula-recognition#7]
When I tried run the command "python evaluate.py -d 2016 -c checkpoints/some-name-0003.pth", one runtime error occured.
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:72] data. DefaultCPUAllocator: not enough memory: you trie
d to allocate 1179648 bytes. Buy new RAM!
Thanks a lot!

**Comment by jungomi** [comment]
It looks like your RAM is full. That's only 1MB so I doubt that you don't have enough RAM available, but I'd assume that some other processes use up all the RAM on your machine. Check your memory usage with a tool like `htop` and free up some memory by terminating those processes.

**Comment by TDYe123** [comment]
Thanks a lot.
