### ISSUE TITLE
testing the model on external image other than CROHME dataset

### ISSUE THREAD

**Issue by dishan14** [jungomi/math-formula-recognition#8]
@jungomi  how do i test this model on an external image other than the provided data set

**Comment by jungomi** [comment]
You can run the evaluation on your own dataset by adding it to the test sets in `evaluate.py`: https://github.com/jungomi/math-formula-recognition/blob/e731ed75ac8b00ee5ef108765b0c0e7a2cef9cf4/evaluate.py#L20-L25

Then you can choose it by specifying the name to the `-d`/`--dataset` option.

The ground truth is a TSV (tab separated values) file, where the first column is the path to the image (relative to the specified root and without the `.png` extension) and the second column is the transcription (expected text). In retrospect, fixing the extension wasn't a good idea, but you could change that by setting `ext=""` in the dataset creation and just include it in the ground truth path.
https://github.com/jungomi/math-formula-recognition/blob/e731ed75ac8b00ee5ef108765b0c0e7a2cef9cf4/evaluate.py#L569-L574

If you just want to predict a single image without ground truth, there is unfortunately no script for that. You'd have to do something like `evaluate.py` but load the image yourself. The code is quite old and complicated, and the model isn't particularly good, so I wouldn't really recommend to go through the hassle to implement that.

**Comment by dishan14** [comment]
@jungomi thanks for your quick help
